### PR TITLE
Add RPC::Client.new

### PR DESCRIPTION
**Pull request by xaviablaza**
## Description
- Add `RPC::Client.new(host, port, username, password, transfer_clazz, rpc, debug)`

## GitHub Issue
#15 

## Pull Request Changes
- Add `attr_reader` to `RPC::Client`
- Add `uri` method to `RPC::Client`

### CODE REVIEW

**Comment by krtschmr** [comment]
@langesi  can you check if you can find anything that seems wrong?

**Comment by krtschmr** [comment]
i wonder if anybody else can say something to this branch and if it's a good idea.
development needs to go on, but i don't want to be the central guy who needs to decide things.

**Review by krtschmr — CHANGES_REQUESTED** [review]
we need to remvoe `.tool-versions` from this merge request and then squash all 5 commits into 1

**Review by krtschmr — COMMENTED** [review]
I've tested this and it worked. I think we can safely merge it if we make it into 1 commit

**Comment by xaviablaza** [comment]
@krtschmr Removed `.tool-versions` and squashed all commits into 1.

**Comment by xaviablaza** [comment]
Can we safely merge in now?

**Comment by krtschmr** [comment]
Will do when I’m back from holiday

**Comment by krtschmr** [comment]
i just tried this out, isn't even working. docs are broken with this. whats going on? :dango:

**Comment by xaviablaza** [comment]
Will double check.

**Comment by krtschmr** [comment]
https://github.com/krtschmr/monero/tree/refactoring

check this. that's how to do it

**Comment by krtschmr** [comment]
i merged already and pushed to rubygems for version 0.0.12

please have a look. test are passing.

**Pull request merged**
